### ISSUE TITLE
[RFE] Remote log viewer of selected device

### ISSUE THREAD

**Issue by DumpySquare** [DumpySquare/vscode-f5-fast#10]
Visibility is important when it comes to many things.  One of the struggles of some of the automated technology is being able to see what, why and when something went wrong.  For declarations, api responses suffice, but when things go really wrong, system logs are needed.

The "Remote Command Execute" allows one to get the output of any log file, but it's a snapshot.  Having a rolling log output would really round out the visibility for any network engineer/developer to see what's going on when developing for F5 automation services.

This might be accomplish-able via a reoccurring API call, but a dedicated channel for live output is ideal

- pretty sure this example only works over Remote SSH
https://marketplace.visualstudio.com/items?itemName=tiansin.logtail

https://unix.stackexchange.com/questions/159033/tail-log-file-on-multiple-machines-over-ssh/159040

**Comment by codygreen** [comment]
While this is a nice idea, I think it hinders the learning process a netops persona will need to become a super-netops persona.  Lets place this in the backlog for now.

**Comment by zinkem5** [comment]
+1

The ability for the user to generate and package artifacts to file bug reports would be extremely useful!

**Comment by DumpySquare** [comment]
In recent versions a feature to enable commands to be executed onConnect provide the platform for automatically connecting to device over ssh and issuing commands when the extension connects over the api.  While this does rely on ssh keys to be setup. It still fit's in nicely to the advanced nature of the request.  closing
