### ISSUE TITLE
Potential name change and global scope extension pack

### ISSUE THREAD

**Issue by DumpySquare** [DumpySquare/vscode-f5-fast#16]
Some users have indicated that FAST may be misleading, since it currently doesn't support any fast functionality, yet, and can/will do much more and just fast. 

Potential Options include: 
 - vscode-f5-automation
 - vscode-f5-ilx
 - vscode-f5-declarative
 - vscode-f5-dec-dev
 - vscode-f5-ats
 - vscode-f5-atc
 - vscode-f5-atc-toolkit
 - vscode-f5-atc-helper
 - vscode-f5-atc-devkit
 - vscode-f5-atc-kit
 - vscode-f5-adm (pronounced "adam"),  f5 (A)utomation (D)eclaration (M)odule/mgmt/maker

Furthermore, this could open the discussion on a wider scope of potential functionality with F5 products and vscode extension functionality.  Similar to the different modules of F5 products, like LTM/GTM/ASM/AFM, extension functionality could be broken into different sub-extensions.  At it's highest level a user could install the F5-extension pack, which would include all functionality (like: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack).

The sub extension pack could be installed all together or individually, allowing the user to tailor the needed functionality and minimize resource utilization (network, local disk space and running resources).

Sub-extensions:
- tcl/iRules/iApps
- AS3/DO/TS
  - or even broken out by each ILX extension
- FAST
- DWAF
- nginx
- cloud services?
- silverline?

**Comment by delgadillo22** [comment]
I prefer vscode-f5-automation as it's descriptive.

**Comment by DumpySquare** [comment]
Talking with the core F5 FAST team and others, and now that the extension actually integrates with FAST, the name seems to be good for now.  Further discussions on this will be tabled for a later date.
