### ISSUE TITLE
[RFE] add utility to convert json<->yaml

### ISSUE THREAD

**Issue by DumpySquare** [DumpySquare/vscode-f5-fast#24]
It would be handy to have a function that could convert yaml to json and json to yaml.

yml is easier to read/write and FAST seems to be able to utilize both also.

**Comment by bitwisecook** [comment]
I use https://www.npmjs.com/package/js-yaml inside `vscode-irule` to generate the syntax json from yaml.

**Comment by DumpySquare** [comment]
functionality added in v2.0, released today
