### ISSUE TITLE
Use new Authentication Provider API in vscode

### ISSUE THREAD

**Issue by bitwisecook** [DumpySquare/vscode-f5-fast#27]
https://github.com/microsoft/vscode/issues/88309
https://code.visualstudio.com/updates/v1_46#_accounts-management

vscode now has a built-in authentication provider so no need to have our own authentication UI

**Comment by DumpySquare** [comment]
Interesting.  Can you expand on the use case for this or provide more context for it's implementation?

**Comment by DumpySquare** [comment]
This seems to be a better more baked in way of managing and syncing credentials for logging into the bigips.  Also seems to be in active development.  will keep an eye on this as the final details shake out and see how this can applied to this extension

**Comment by DumpySquare** [comment]
this seems to be an experimental feature for vscode at this time.  moving to backlog for later review.
