### ISSUE TITLE
[RFE] support remote authentication of bigip devices

### ISSUE THREAD

**Issue by DumpySquare** [DumpySquare/vscode-f5-fast#38]
user needs to be able to an F5 what utilizes remote authentication

fix will be related to #34 

Solution:
- The idea is to check for auth provider during the initial device connect (when discovering installed ILX plugins).

provide creds using basic auth to the following url, it should provide what the configured logon provider 

/mgmt/tm/auth/source

{
    "username":"<username>",
    "password":"<password>",
    "logonProviderName":"tmos"
}

"fallback":"false","type":"active-directory"

curl: 

curl -s -k -u admin:changeme -X POST -H "Content-Type: application/json" -d '{ "username": "awesomeUser", "password": "changeme1234", "loginProviderName": "tmos"}' https://x.x.x.x/mgmt/shared/authn/login

**Comment by vinnie357** [comment]
suggesting query this endpoint before, requesting a token.

```bash
curl -k -u admin:admin https://192.168.20.24/mgmt/tm/auth/source
```
"thanks @Mikej81" - https://github.com/Mikej81/PowerSRG/blob/master/SRG_Powershell_v1.0.ps1#L113

example responses:
```bash
# local

{"kind":"tm:auth:source:sourcestate","selfLink":"https://localhost/mgmt/tm/auth/source?ver=14.1.2.1","fallback":"false",**"type":"local"**}

# AD
{"kind":"tm:auth:source:sourcestate","selfLink":"https://localhost/mgmt/tm/auth/source?ver=14.1.2.1","fallback":"false"**,"type":"active-directory"**}

# radius
{"kind":"tm:auth:source:sourcestate","selfLink":"https://localhost/mgmt/tm/auth/source?ver=14.1.2.1","fallback":"false","type":"radius"}
```
# maps to token requests here:
https://github.com/DumpySquare/vscode-f5-fast/search?q=logon+provider&unscoped_q=logon+provider

"**logonProviderName**": "provider"

**Comment by Mikej81** [comment]
Use Basic.

**Comment by DumpySquare** [comment]
functionality added in v2.0, released today
