### ISSUE TITLE
[RFE] Support for single NIC 8443

### ISSUE THREAD

**Issue by focrensh** [DumpySquare/vscode-f5-fast#5]
Currently there does not seem to be support for alternative ports.

admin@test.com:8443

```Already exists or invalid format: <user>@<host/ip>```

**Comment by DumpySquare** [comment]
v0.1.7 was just published to marketplace to accommodate this use case.  Please confirm when you can

**Comment by zinkem** [comment]
Single NIC works for me in newest version

**Comment by focrensh** [comment]
Yes it does, closing.
