### ISSUE TITLE
Tenants are not showing properly when using vscode-f5-fast with BIG-IQ

### ISSUE THREAD

**Issue by rjouhann** [DumpySquare/vscode-f5-fast#58]
The tenants are not showing properly when using vscode-f5-fast with BIG-IQ.

It shows 0, 1, 2 instead of tenant names.

![image](https://user-images.githubusercontent.com/25542366/89924976-9ac01880-dbb7-11ea-8e99-44414101d1d4.png)

**Comment by DumpySquare** [comment]
@rjouhann, I started looking into this but it seems as3 declarations are managed in a couple different ways within bigiq.  

Can you provide any more details on the declarations and how your sending them to bigiq?  Maybe provide the output from a GET on /mgmt/shared/appsvcs/declare?

Also, what version of bigiq?

**Comment by rjouhann** [comment]
@DumpySquare this would be with BIG-IQ 7.0 and 7.1.

Let me share with you an example of a GET /mgmt/shared/appsvcs/declare from BIG-IQ via email. But it looks like the declarations from each devices are in an array.

Let me know if you need other info, I can also share with you my lab on F5 intranet.
