### ISSUE TITLE
[RFE] Support ILX containers

### ISSUE THREAD

**Issue by DumpySquare** [DumpySquare/vscode-f5-fast#6]
ILX docker containers have not been tested.  Like BIG-IQ, it is a good possibility it will just work, but some minor testing, adjustments may be needed.  This usage scenario needs to be tested and documented.

**Comment by codygreen** [comment]
get clarification on ILX container LTS.

**Comment by DumpySquare** [comment]
There are discussions on the LTS of ILX containers currently going on.  Moving to backlog
