### ISSUE TITLE
Update Bad Password

### ISSUE THREAD

**Issue by codygreen** [DumpySquare/vscode-f5-fast#62]
I cannot update a bad password for a BIG-IP. Can you add this as a right-click option?  Deleting the BIG-IP did not clear the password from the config either.

**Comment by DumpySquare** [comment]
Yes.   Had this problem with another person yesterday.  Will get worked out ASAP

Need to add right-click option on host item to clear password, add clear password to delete device function

**Comment by DumpySquare** [comment]
fixed in v2.3
